---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: operators/gitlab/overlays/latest
    repoURL: >-
      git@github.com:ahussey-redhat/cicd-gitops-demo.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: false
      selfHeal: true