---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: ssd
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  deviceInclusionSpec:
    deviceMechanicalProperties:
      - NonRotational
    deviceTypes:
      - disk
      - part
    minSize: 1Gi
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - sno.k8s.idm.hussdogg.com
  storageClassName: ssd
  volumeMode: Block
---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: hdd
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  deviceInclusionSpec:
    deviceMechanicalProperties:
      - Rotational
    deviceTypes:
      - disk
      - part
    minSize: 1Gi
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - sno.k8s.idm.hussdogg.com
  storageClassName: hdd
  volumeMode: Block