---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: openshift-local-storage
  labels:
    kubernetes.io/metadata.name: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
