apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi
  namespace: openshift
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/ubi:latest
      name: latest
      referencePolicy:
        type: Source