---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspacesoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspacesoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
