---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: openshift-gitops
  labels:
    name: gitlab
spec:
  project: default
  source:
    repoURL: git@github.com:ahussey-redhat/cicd-gitops-demo.git
    targetRevision: develop
    path: operators/gitlab
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
      - kube-controller-manager
