---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: operators/vault/overlays/helm
    repoURL: >-
      https://github.com/ahussey-redhat/cicd-gitops-demo.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
