---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mattermost
  namespace: openshift-operators
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: mattermost
  objectBucketName: mattermost
  storageClassName: openshift-storage.noobaa.io