---
kind: Mattermost
apiVersion: installation.mattermost.com/v1beta1
metadata:
  name: mattermost-cluster
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  version: 7.9.1
  replicas: 1
  image: docker.io/mattermost/mattermost-enterprise-edition
  imagePullPolicy: Always
  ingress:
    enabled: true
    host: mattermost.apps.k8s.prod.mid.local
  database:
    external:
      secret: mattermost-postgres
  fileStore:
    operatorManaged:                            # Operator managed file store allows configuration of replicas, storage size and resource requirements. If the `size` is specified, it will override those values.
      replicas: 1
      resources:
        requests:
          cpu: 150m
          memory: 512Mi
      storageSize: 50Gi