---
kind: Mattermost
apiVersion: installation.mattermost.com/v1beta1
metadata:
  name: mattermost-cluster
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: 7.9.4
  replicas: 1
  image: docker.io/mattermost/mattermost-enterprise-edition
  imagePullPolicy: Always
  ingress:
    enabled: false
    host: we.use.routes.here
  database:
    external:
      secret: mattermost-postgres
  fileStore:
    external:
      url: s3.openshift-storage.svc:443
      bucket: mattermost
      secret: mattermost-s3
