# The values below are for the mattermost operator
mattermostOperator:
  enabled: true
  replicas: 1
  rbac:
    create: true
  serviceAccount:
    create: true
  env:
    maxReconcilingInstallations: 20
    maxReconcilingConcurrency: 10
    requeuOnLimitDelay: 20s
  image:
    repository: docker.io/mattermost/mattermost-operator
    tag: master
    pullPolicy: Always
  args:
    - --enable-leader-election
    - --metrics-addr=0.0.0.0:8383
  privateRegistry:
    enabled: false
    imagePullSecret: <name of the secret>