apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: openshift-operators

bases:
  - ../../../operators/pipelines/overlays/latest
  - ../../../operators/gitlab/overlays/latest
  - ../../../operators/devspaces/overlays/latest

