---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: operators/local-storage-operator
    repoURL: >-
      git@github.com:ahussey-redhat/cicd-gitops-demo.git
    targetRevision: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true