---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat Quay"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: quay-operator