---
- name: Configure cluster
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: deploy application
      kubernetes.core.k8s:
        src: applications/hello-world.yml
