---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-operators
resources:
  - ../../base
patchesJson6902:
  - target:
      group: operators.coreos.com
      kind: Subscription
      name: amq-streams
      namespace: openshift-operators
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable
