---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: demo
  labels:
    name: hello-world
spec:
  project: default
  source:
    repoURL: https://github.com/ahussey-redhat/cicd-gitops-demo.git
    targetRevision: main
    path: applications/hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
      - kube-controller-manager
