apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/local-storage-operator.yml
  - applications/lvms-operator.yml
  - applications/pipelines-operator.yml
  # - applications/acm-operator.yml
  - applications/devspaces-operator.yml
  # - applications/gitlab-operator.yml
  - applications/rhsso.yml
  # - applications/vault-operator.yml
  # Other components
  - misc/rh-subscription-builds.yml
