---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  chart:
    values:
      certmanager:
        install: false
      global:
        hosts:
          domain: apps.k8s.dev.local
        ingress:
          configureCertmanager: false
    version: 6.9.3
