---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  chart:
    values:
      certmanager:
        install: true
        email: ahussey@redhat.com
      global:
        hosts:
          domain: apps.test.lbjg.p1.openshiftapps.com
        ingress:
          configureCertmanager: true
    version: 6.11.0
