---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvm-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: lvm-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
